language: python
matrix:
  include:
    - name: "Python 3.6 on Linux"
      python: 3.6
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
      env:
        - COVERAGE=true    # coverage test are only run in python 3.7
        - PEP8=true        # pep8 checks are only run in python 3.7
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python3 --version=3.7.3
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Coverage and pep 8 tests on Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
      env:
        - PEP8COVERAGE=true    # coverage test are only 
install:
  - pip3 install --upgrade pip cython numpy || pip3 install --upgrade --user pip cython numpy # all three OSes agree about 'pip3'
  - |
      if [[ $PEP8COVERAGE == true ]]; then
        pip3 install flake8 || pip3 install --user flake8
        pip3 install codecov pytest-cov || pip3 install --user codecov pytest-cov
      fi

# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
# python3 setup.py test || python setup.py test;
script:
    - |
      if [[ $PEP8COVERAGE == true ]]; then
        flake8 --exit-zero skfda;
        coverage run --source=skfda/ setup.py test;
      else
        pytest || pytest;
      fi


after_success:
    - |
      if [[ $PEP8COVERAGE == true ]]; then
        codecov
      fi
